# How long till crumblestone decays, in seconds
# default: 300 (5 minutes)
decay-time-seconds: 300
# What block Crumblestone will display as (does not change behavior)
# default: COARSE_DIRT
material: COARSE_DIRT