name: Crumblestone
main: space.retri.crumblestone.CrumblestonePlugin
version: '${version}'
api-version: 1.19
description: Adds Crumblestone, a cheap temporary block that decays over time.
author: Retribyte
website: https://minecraft.retri.space
